version: '2'
services:
    ghostylink:
        image: docker.io/ghostylink/ghostylink
        ports:
         - "__PORT:80"         
        volumes:
         - ${PWD}/data/:/var/lib/mysql:z
         - ${PWD}/conf/:/conf
         - ${PWD}/logs/:/log
        links:
         - smtp
        expose:
         - "25"
    smtp:
        image: docker.io/tvial/docker-mailserver        
        domainname: __HOST
        ports:
          - "1025:25"
          - "143:143"
          - "587:587" 
          - "993:993"
        expose:
          - "25"
        volumes:
          - ${PWD}/postfix:/tmp/postfix:ro